import os
import pickle
import pandas as pd
import numpy as np
from flask import Flask, render_template, request, jsonify, send_file

app = Flask(__name__)

# Load models and configurations
MODEL_PATH = os.path.join('model', 'model.pkl')
SCALER_PATH = os.path.join('model', 'scaler.pkl')
SELECTED_FEATURES_PATH = os.path.join('model', 'selected_features.pkl')

try:
    with open(MODEL_PATH, 'rb') as f:
        model = pickle.load(f)
    with open(SCALER_PATH, 'rb') as f:
        scaler = pickle.load(f)
    with open(SELECTED_FEATURES_PATH, 'rb') as f:
        selected_features = pickle.load(f)
    print("Models, scaler, and features loaded successfully.")
except Exception as e:
    print(f"Error loading models or pickles: {e}")
    model, scaler, selected_features = None, None, None

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/report')
def report():
    # Serve the static HTML report generated by Evidently without parsing it as a Jinja template
    return send_file(os.path.join('templates', 'report.html'))

@app.route('/predict', methods=['POST'])
def predict():
    if not model or not scaler or not selected_features:
        return jsonify({'error': 'Model or scaler not loaded properly on the server.'}), 500

    try:
        data = request.json
        if not data:
            return jsonify({'error': 'No input data provided'}), 400

        # Retrieve and parse user inputs
        gender = data.get('gender') # Male, Female
        married = data.get('married') # Yes, No, unknown
        dependents = data.get('dependents') # 0, 1, 2, 3+, unknown
        education = data.get('education') # Graduate, Not Graduate
        self_employed = data.get('self_employed') # Yes, No
        applicant_income = float(data.get('applicant_income', 0))
        coapplicant_income = float(data.get('coapplicant_income', 0))
        loan_amount = float(data.get('loan_amount', 0))
        loan_amount_term = float(data.get('loan_amount_term', 360))
        credit_history = data.get('credit_history') # Yes, No
        property_area = data.get('property_area') # Rural, Semiurban, Urban

        # Numerical scaling first
        # Scaler expects columns in exact order: ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term']
        numeric_cols = ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term']
        raw_numeric_df = pd.DataFrame([[applicant_income, coapplicant_income, loan_amount, loan_amount_term]], columns=numeric_cols)
        scaled_numeric = scaler.transform(raw_numeric_df)
        scaled_numeric_df = pd.DataFrame(scaled_numeric, columns=numeric_cols)

        # Full set of 19 encoded features as expected originally by X_train columns:
        # ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Gender_Male', 
        #  'Education_Not Graduate', 'Self_Employed_Yes', 'Credit_History_Yes', 'Married_No', 'Married_Yes', 
        #  'Married_unknown', 'Dependents_0', 'Dependents_1', 'Dependents_2', 'Dependents_3+', 'Dependents_unknown', 
        #  'Property_Area_Rural', 'Property_Area_Semiurban', 'Property_Area_Urban']
        
        encoded_dict = {
            'ApplicantIncome': scaled_numeric_df['ApplicantIncome'].iloc[0],
            'CoapplicantIncome': scaled_numeric_df['CoapplicantIncome'].iloc[0],
            'LoanAmount': scaled_numeric_df['LoanAmount'].iloc[0],
            'Loan_Amount_Term': scaled_numeric_df['Loan_Amount_Term'].iloc[0],
            'Gender_Male': 1 if gender == 'Male' else 0,
            'Education_Not Graduate': 1 if education == 'Not Graduate' else 0,
            'Self_Employed_Yes': 1 if self_employed == 'Yes' else 0,
            'Credit_History_Yes': 1 if credit_history == 'Yes' else 0,
            'Married_No': 1 if married == 'No' else 0,
            'Married_Yes': 1 if married == 'Yes' else 0,
            'Married_unknown': 1 if married == 'unknown' else 0,
            'Dependents_0': 1 if dependents == '0' else 0,
            'Dependents_1': 1 if dependents == '1' else 0,
            'Dependents_2': 1 if dependents == '2' else 0,
            'Dependents_3+': 1 if dependents == '3+' else 0,
            'Dependents_unknown': 1 if dependents == 'unknown' else 0,
            'Property_Area_Rural': 1 if property_area == 'Rural' else 0,
            'Property_Area_Semiurban': 1 if property_area == 'Semiurban' else 0,
            'Property_Area_Urban': 1 if property_area == 'Urban' else 0,
        }

        # Convert to DataFrame
        full_df = pd.DataFrame([encoded_dict])

        # Filter and order columns according to selected_features.pkl
        input_model_df = full_df[selected_features]

        # Make prediction
        prediction = int(model.predict(input_model_df)[0])
        probabilities = model.predict_proba(input_model_df)[0].tolist()

        return jsonify({
            'prediction': prediction,
            'probability': probabilities, # Index 0: Rejected, Index 1: Approved
            'status': 'Approved' if prediction == 1 else 'Rejected'
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)
